/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.DAO.EspecialidadeDAO;


/**
 *
 * @author 22282225
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        initPanel();
        
        
    }
    //Atributos da class
    JPanelEspecialidades panelEspecialidades;
    
    //constantes
    private final int pos_X = 0;
    private final int pos_Y = 170;
    private final int LARGURA = 800;
    private final int ALATURA = 290;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        tituloDoHeader = new javax.swing.JLabel();
        iconeDaAgenda = new javax.swing.JLabel();
        buttonAgendamento = new javax.swing.JButton();
        buttonPasciente = new javax.swing.JButton();
        buttonMédico = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonSaida = new javax.swing.JButton();
        buttonPlanoDeSaude = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        labelNomedaEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setLayout(null);

        tituloDoHeader.setBackground(new java.awt.Color(0, 0, 0));
        tituloDoHeader.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        tituloDoHeader.setForeground(new java.awt.Color(255, 255, 255));
        tituloDoHeader.setText("Sistema para agendamento de Consulta");
        header.add(tituloDoHeader);
        tituloDoHeader.setBounds(80, 40, 420, 26);

        iconeDaAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/calendario (1).png"))); // NOI18N
        header.add(iconeDaAgenda);
        iconeDaAgenda.setBounds(6, 6, 90, 88);

        getContentPane().add(header);
        header.setBounds(0, 0, 810, 110);

        buttonAgendamento.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/agenda.png"))); // NOI18N
        buttonAgendamento.setToolTipText("Agendamento");
        buttonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgendamento);
        buttonAgendamento.setBounds(100, 110, 90, 40);

        buttonPasciente.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonPasciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/paciente.png"))); // NOI18N
        buttonPasciente.setToolTipText("Paciente");
        buttonPasciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPascienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPasciente);
        buttonPasciente.setBounds(190, 110, 90, 40);

        buttonMédico.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonMédico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/medico.png"))); // NOI18N
        buttonMédico.setToolTipText("Médico");
        buttonMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMédicoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMédico);
        buttonMédico.setBounds(280, 110, 100, 40);

        buttonEspecialidades.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonEspecialidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/recompensa.png"))); // NOI18N
        buttonEspecialidades.setToolTipText("Especialidades");
        buttonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades);
        buttonEspecialidades.setBounds(380, 110, 120, 40);

        buttonSaida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/saida-de-emergencia.png"))); // NOI18N
        buttonSaida.setToolTipText("Saír");
        getContentPane().add(buttonSaida);
        buttonSaida.setBounds(620, 110, 180, 40);

        buttonPlanoDeSaude.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/plano-de-saude.png"))); // NOI18N
        buttonPlanoDeSaude.setToolTipText("Plano De Saúde");
        buttonPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanoDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlanoDeSaude);
        buttonPlanoDeSaude.setBounds(500, 110, 120, 40);

        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/homet-32.png"))); // NOI18N
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHome);
        buttonHome.setBounds(0, 110, 100, 40);

        panelHome.setBackground(new java.awt.Color(102, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N
        panelHome.setLayout(null);

        labelNomedaEmpresa.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelNomedaEmpresa.setText("TroiaV");
        panelHome.add(labelNomedaEmpresa);
        labelNomedaEmpresa.setBounds(10, 30, 90, 26);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Sistema de Agentamento Para consulta");
        panelHome.add(jLabel2);
        jLabel2.setBounds(10, 50, 240, 14);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("Dados para contatos:");
        panelHome.add(jLabel3);
        jLabel3.setBounds(10, 100, 150, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        panelHome.add(jPanel1);
        jPanel1.setBounds(0, 70, 800, 10);

        jLabel4.setText("E-mail: TroiaV5@gmail.com");
        panelHome.add(jLabel4);
        jLabel4.setBounds(10, 120, 160, 16);

        jLabel5.setText("Telefone: (11) 4002-8922");
        panelHome.add(jLabel5);
        jLabel5.setBounds(10, 140, 140, 16);

        jLabel6.setText("Site: www.Troia.com.br");
        panelHome.add(jLabel6);
        jLabel6.setBounds(10, 160, 140, 16);

        getContentPane().add(panelHome);
        panelHome.setBounds(0, 170, 800, 290);

        setSize(new java.awt.Dimension(816, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgendamentoActionPerformed

    private void buttonMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMédicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMédicoActionPerformed

    private void buttonPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanoDeSaudeActionPerformed
        
    }//GEN-LAST:event_buttonPlanoDeSaudeActionPerformed

    private void buttonPascienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPascienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPascienteActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        panelEspecialidades.setVisible(false);
        panelHome.setVisible(true);
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidadesActionPerformed
        panelEspecialidades.setVisible(true);
        panelHome.setVisible(false);
    }//GEN-LAST:event_buttonEspecialidadesActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgendamento;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonMédico;
    private javax.swing.JButton buttonPasciente;
    private javax.swing.JButton buttonPlanoDeSaude;
    private javax.swing.JButton buttonSaida;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconeDaAgenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNomedaEmpresa;
    private javax.swing.JPanel panelHome;
    private javax.swing.JLabel tituloDoHeader;
    // End of variables declaration//GEN-END:variables

    private void initPanel(){
    
       panelEspecialidades  = new JPanelEspecialidades();
    
        panelEspecialidades.setBounds(
                pos_X,
               pos_Y,
               LARGURA,
               ALATURA);
        
       getContentPane().add(panelEspecialidades);
       panelEspecialidades.setVisible(false);
    
    }
}
